# Tutorial

Let's start with the classic tutorial

# Creating your Vocabulary

To create your own vocabulary, you need to pass two params, the settings and the processed path.
Settings path enables you to work with stopwords. The stopwords needs to be a txt file with format language.txt.
For example, en-gb.txt. The processed path basicaly points to where the processed file will be saved.

```python
  from matchup.structure.Vocabulary import Vocabulary

  settings = "path/to/settings/folder"
  processed = "path/to/generate/response"
  vocabulary = Vocabulary(settings_path=settings, processed_path=processed)
  vocabulary.import_file("path/to/file")
  vocabulary.import_folder("path/to/folder")
  vocabulary.generate_vocabulary()
  vocabulary.save()

```

At this point, you're able to make queries. If you already save it once, you can just do it, after instance Vocabulary

```python
vocabulary.import_vocabulary()
```

# Doing Queries

To make queries, you can set four IR Models and it params. This description will be done in the next update.
For now, it's just create without any parameters, like

```python
query = Query(vocabulary=vocabulary)
query.ask()
solution = query.search()
print(solution)
```

You can also pass an answer named param to the ask method, if you don't want to make an IO operation.

A Solution object are generated by the query, and the object has the rank of
the documents through a similarity calculation.
