# Tutorial #

Let's start with the classic example of creating a vocabulary:

```python
from matchup.structure.Vocabulary import Vocabulary

  settings = 'path/to/settings/folder' # your stopwords path
  processed = 'path/to/generate/response' # processed file will be generated here
  vocabulary = Vocabulary(settings_path=settings, processed_path=processed)
  vocabulary.import_file('path/to/file') # process one file
  vocabulary.import_folder('path/to/folder') # process every file on this folder
  vocabulary.generate_vocabulary()
  vocabulary.save()

```

[Demo](https://github.com/reingart/pyfpdf/raw/master/tutorial/tuto1.pdf)

At this point, you're able to make queries. If you already save it once, you can just do it, after instance Vocabulary

```python
vocabulary.import_vocabulary()
```

To make queries, you can set four IR Models and it params. This description will be done in the next update.
For now, it's just create without any parameters, like

```python
query = Query(vocabulary=vocabulary)
query.ask() # you can also pass the answer, without an IO operation.
solution = query.search()
print(solution)
```

A Solution object are generated by the query, and the object has the rank of
the documents through a similarity calculation.
