language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install coverage
  - pip install codecov
install:
  - pip install ".[tests]" . # install package + test dependencies
script: coverage run -m unittest tests/unit/main.py tests/functional/main.py # run tests
after_success:
  - codecov
  - codecov --token=9626b75c-1b45-4319-9f08-81199b875813