name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install codecov
        pip install pdfminer
    - name: Test with unittest
      run: |
        coverage run -m unittest tests/unit/main.py tests/functional/main.py
        codecov
        codecov --token=9626b75c-1b45-4319-9f08-81199b875813
        coverage report -m
